name: charlescd-prodrelease

on:
  release:
    types:
      - released
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Update helm dependencies
        uses: WyriHaximus/github-action-helm3@v2.1.3
        with:
          exec: helm dependency update ./install/helm-chart

      - name: Zup Settings dev
        run: |
          cat <<-EOF > values-charles-dev.yaml
          ${{ secrets.VALUES_CHARLES_DEV }}
          EOF

      - name: Deploy dev
        uses: WyriHaximus/github-action-helm3@v2.1.3
        with:
          exec: helm upgrade charleshardcore ./install/helm-chart/ --namespace=salezao --install --wait --atomic --values=./values-charles-dev.yaml --timeout=3600
          kubeconfig: '${{ secrets.KUBECONFIG_DEV }}'
